[{"name":"HND-796mmsub",
"info":"မြန်မာစာတန်းထိုး
‌အဖေက နောက်အိမ်ထောင် ပြုလိုက်လို့ မေမေလေးမှာ ချစ်စရာကောင်းတဲ့ သမီးပျိုလေး တစ်ယောက်ပါလာခဲ့ပါတယ်
တစ်နေ့မှာ မိဘနှစ် ခရီးထွက်တုန်း အိမ်မှာ ညီမလေးနဲ့ နှစ်ယောက်တည်း ကျန်ခဲ့တဲ့အချိန်မှာတော့

မျက်နှာကို ချွေး၊ တံတွေးနဲ့ ရွှံ့တွေဖုံးပြီး ငါ့ကို ရွံနေသလိုလို အမြဲဆက်ဆံနေတဲ့ ငါ့ရဲ့ Stepsister (မိထွေးသမီး)ကို လက်စားချေခြင်း 
မငါးသမီးနာမည် Yui Nagase",
"watch":"https://awscc3001.r18.com/litevideo/freepv/h/hnd/hnd00796/hnd00796_dmb_w.mp4",
"download":"https://www.mediafire.com/file/i6cg8v3ttdinduw/HND_796-HD.mp4/file",
"photo1":"https://i.imgur.com/YHf7AjB_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/hnd00796/hnd00796pl.jpg",
"photo3":"https://pics.r18.com/digital/video/hnd00796/hnd00796jp-5.jpg",
"photo4":"https://pics.r18.com/digital/video/hnd00796/hnd00796jp-3.jpg",
"photo5":"https://pics.r18.com/digital/video/hnd00796/hnd00796jp-6.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"SDMU-817mmsub",
"info":"မြန်မာစာတန်းထိုး
MC ကလူသာငယ်တာ အစွယ်စုံပေါက်နေတဲ့ကောင်လေးတစ်ယောက်ဖြစ်ပြီး ကောင်မလေးချောချောလေးတွေရှေ့မှာဆို မခုတ်တတ်တဲ့ကြောင်ငယ်လေးလိုလဲ သနားစရာကောင်းအောင်နေတတ်ပါသေးတယ် တစ်နေ့မှာတော့ အိမ်ကလူတွေခရီးထွက်တော့ အကို့ဇနီးမရီးအထန်မလေးနဲ့ တစ်အိမ်တည်းနေခဲ့ရပါတယ် အကို့ဇနီးအထန်မလေးနာမည်က Hana ဖြစ်ပြီး လုံးကြီးပေါက်လှသူမက မူယာမာယာများတဲ့အပြင် ကောင်လေးတွေကို ဆွဲစားလေ့ရှိသူပါ Hana တစ်ယောက် မခုတ်တတ်တဲ့ကြောင်လေးဟန်ဆောင်နေတဲ့ MC ကို လူပျိုပေါက်လေးအထင်နဲ့ ဆွဲစားဖို့ကြိုးစားရာမှာ လူသာငယ်ပေမယ့် အထာကျတဲ့ MC က Hana ကိုဘယ်လိုပညာခန်းပြမလဲဆိုတာကတော့......",
"watch":"https://awscc3001.r18.com/litevideo/freepv/1/1sd/1sdmu00817/1sdmu00817_dmb_w.mp4",
"download":"https://www.mediafire.com/file/mlvuanqwov6ix1k/SDMU-817-HD.mp4/file",
"photo1":"https://i.imgur.com/VnIYWRF_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/1sdmu00817/1sdmu00817pl.jpg",
"photo3":"",
"photo4":"",
"photo5":"",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"VOSS-083mmsub",
"info":"မြန်မာစာတန်းထိုး",
"watch":"https://awscc3001.r18.com/litevideo/freepv/v/vos/voss00083/voss00083_dmb_w.mp4",
"download":"https://www.mediafire.com/file/w62hazw868k85su/VOSS+083-HD.mp4/file",
"photo1":"https://i.imgur.com/slJWgFn_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/voss00083/voss00083pl.jpg",
"photo3":"https://pics.r18.com/digital/video/voss00083/voss00083jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/voss00083/voss00083jp-10.jpg",
"photo5":"https://pics.r18.com/digital/video/voss00083/voss00083jp-16.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"HTMS-119mmsub",
"info":"မြန်မာစာတန်းထိုး
ဇာတ်လမ်းလေးကတော့ ရွှေရင်အစုံဖွံ့ထွားလှတဲ့ မင်းသမီး ၅ယောက်ရဲ့ ဇာတ်လမ်းတို ၅ပုဒ်ပါဝင်ပြီး တစ်ယောက်ချင်းစီရဲ့ ထန်ပုံထန်နည်းလေးတွေကို ခါတိုင်းနဲ့မတူ တမူထူးခြားအောင် ဖော်ပြထားတဲ့ ဇာတ်လမ်းသွားလေးပါ
ဇာတ်လမ်းတို ၁ - အစားပုတ်သလို အစားလဲပုတ်တဲ့ အမကြီး
ဇာတ်လမ်းတို ၂ - ဟိုဘက်ခန်းက ဦးလေးကြီးအိမ် ယောက်ျားမသိအောင် ခိုးသွားတဲ့ အမျိုးသမီး
ဇာတ်လမ်းတို ၃ - နေ့ခင်းကြောင်တောင်ထန်နေလို့ ဘဲကြီးအခန်းဇွတ်ဝင်တဲ့ အကိတ်မလေး
ဇာတ်လမ်းတို ၄ - ခွဲစိတ်ခန်းက ဆရာမလေးရဲ့ ဆေးရုံအုပ်ကစ လူနာပါမချန် ဆွဲစားပုံ
ဇာတ်လမ်းတို ၅ - မွေးစားအဖေအိမ် ပိုက်ဆံသွားတောင်းသော ကောင်မလေးအကြောင်း..",
"watch":"https://awscc3001.r18.com/litevideo/freepv/h/htm/htms119/htms119_dmb_w.mp4",
"download":"https://www.mediafire.com/file/2ole4t8vgu0ohmj/HTMS_119-SD.mp4/file",
"photo1":"https://i.imgur.com/Mov9oPt_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/htms00119/htms00119pl.jpg",
"photo3":"https://pics.r18.com/digital/video/htms00119/htms00119jp-20.jpg",
"photo4":"https://pics.r18.com/digital/video/htms00119/htms00119jp-11.jpg",
"photo5":"https://pics.r18.com/digital/video/htms00119/htms00119jp-14.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"XVSR-558mmsub",
"info":"မြန်မာစာတန်းထိုး
ဒီဇာတ်လမ်းလေးကတော့ ယောက်ျားအိမ်မှာမရှိတုန်း ကောင်လေးတွေနဲ့နောက်မီးလင်းတတ်တဲ့ မိန်းမချောလေးကို ပညာကောင်းကောင်းပေးတဲ့ ကောင်လေးတစ်ယောက်အကြောင်းပါ
MC တို့ဟိုဘက်ခန်းက ဆော်ချောချောလေးတစ်ယောက်က  အိမ်မှာယောက်ျားမရှိရင်မရှိသလို  ဘဲတွေကို  ခေါ်ခေါ်လာတတ်ပါတယ် ဒါတွေကိုမြင်တွေ့နေရတဲ့ MC က ဗွီဒီယိုချောင်းရိုက်ထားပြီး သူမယောက်ျားခရီးထွက်တုန်း ဆော်လေးကို အကြပ်ကိုင်ခဲ့ပါတော့တယ် သူ့အကြောင်းတွေအကုန်သိသွားတဲ့ MC နဲ့တွေ့မှ စားဆော်လေးဘယ်လို ဝပ်ဆင်းသွားရလဲဆိုတာကတော့....",
"watch":"https://awscc3001.r18.com/litevideo/freepv/x/xvs/xvsr00558/xvsr00558_dmb_w.mp4",
"download":"https://www.mediafire.com/file/vremh1nj227zl2d/XVSR_558-HD.mp4/file",
"photo1":"https://i.imgur.com/fXQ9Q1F_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/xvsr00558/xvsr00558pl.jpg",
"photo3":"https://pics.r18.com/digital/video/xvsr00558/xvsr00558jp-2.jpg",
"photo4":"https://pics.r18.com/digital/video/xvsr00558/xvsr00558jp-5.jpg",
"photo5":"https://pics.r18.com/digital/video/xvsr00558/xvsr00558jp-8.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"WANZ-429mmsub",
"info":"မြန်မာစာတန်းထိုး
ဇာတ်လမ်းလေးကတော့ 
အရွယ်ရောက်ခါစ သမီးဖြစ်သူက ဘဲထားတတ်နေပါပြီ ဘဲကို အမေဖြစ်သူနဲ့ မိတ်ဆက်ပေးပြီး အိမ်ခေါ်စာလုပ်သလိုလိုနဲ့ ဟွာလုပ်ဖို့ကြိုးစားခဲ့တဲ့ အပျိုပေါက်သမီးလေးကို ငယ်ရွယ်သေးချိန်မှာ ဒါတွေမလုပ်ဖို့ စာကိုသာအာရုံစိုက်သင့်ကြောင်း အမေတစ်ယောက်အနေနဲ့ ပြောဆိုဆုံးမခဲ့ပါတယ် တစ်ဖက်မှာတော့ Mizuno  လေးဟာ ဇောင်းထနေတဲ့သူမရဲ့ဘဲကို အိမ်ခေါ်ပြီး နှစ်ယောက်ချင်းတွေ့ကာ ဇောင်းမထအောင် ပညာအမျိုးမျိုးပေးကာ ဆုံးမခဲ့ပါတော့တယ်....",
"watch":"https://awscc3001.r18.com/litevideo/freepv/w/wan/wanz00429/wanz00429_dmb_w.mp4",
"download":"https://www.mediafire.com/file/mygorvhcqavhypv/WANZ_429-SD.mp4/file",
"photo1":"https://i.imgur.com/irYCiow_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://img2.javmost.com/file_image/WANZ-429.jpg",
"photo3":"https://pics.dmm.co.jp/digital/video/wanz00429/wanz00429jp-1.jpg",
"photo4":"https://pics.dmm.co.jp/digital/video/wanz00429/wanz00429jp-3.jpg",
"photo5":"https://pics.dmm.co.jp/digital/video/wanz00429/wanz00429jp-7.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"SSNI-679mmsub",
"info":"မြန်မာစာတန်းထိုး
ငါရဲ့အချစ်ဆုံး သူငယ်ချင်းကျော်ကြီးက ငါ့ရည်းစားကို ငါမသိတုန်း အပီလိုးဖြဲခဲ့သည်
မင်းသမီးနာမည် Yura Kano

Vip memberတွေအတွက် သီးသန့် တင်ပေးထားတဲ့ဇာတ်ကားဖစ်ပါတယ်",
"watch":"https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00679/ssni00679_dmb_w.mp4",
"download":"https://www.mediafire.com/file/w1alb0a30i8ddpp/SSNI-679.mp4/file",
"photo1":"https://i.imgur.com/yCr9ZZR_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/ssni00679/ssni00679pl.jpg",
"photo3":"https://pics.r18.com/digital/video/ssni00679/ssni00679jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/ssni00679/ssni00679jp-2.jpg",
"photo5":"https://pics.r18.com/digital/video/ssni00679/ssni00679jp-3.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"JUL-252mmsub",
"info":"မြန်မာစာတန်းထိုး
အလုပ်သမားဝန်ထမ်း ဖစ်သူရဲ့ ဇနီးကို သူဌေးဖစ်သူက ဝိုက်တဲ့ဇာတ်လမ်းလေးပါ
သူဌေးကိုမုန်းတယ် ကျွန်မခင်ပွန်းကို မညာမတာ အလုပ်ခိုင်းတဲ့အပြင် ကျွန်မကိုလည်း အတင်းအဓမ္မ ဖောင်းဒိုင်းကျွေးသည်
မင်းသမီးနာမည် Miho Tono",
"watch":"https://awscc3001.r18.com/litevideo/freepv/j/jul/jul00252/jul00252_dmb_w.mp4",
"download":"https://www.mediafire.com/file/5fglbnhbo6gv7h2/JUL-252.mp4/file",
"photo1":"https://i.imgur.com/g3Oszre_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/jul00252/jul00252pl.jpg",
"photo3":"https://pics.r18.com/digital/video/jul00252/jul00252jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/jul00252/jul00252jp-2.jpg",
"photo5":"https://pics.r18.com/digital/video/jul00252/jul00252jp-3.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"JUL-485mmsub",
"info":"မြန်မာစာတန်းထိုး
ဒီဇာတ်လမ်းလေးကတော့ အလုပ်ဝင်ခါစ ကောင်မလေးတစ်ယောက်ရဲ့ အလုပ်သစ်က အတွေ့အကြုံအသစ်လေးတွေအကြောင်းပဲဖြစ်ပါတယ်
ခုမှ အလုပ်စဝင်တဲ့ကောင်မလေးငယ်ငယ်လေးတစ်ယောက်က အလုပ်မှာ မန်နေဂျာကြီးရဲ့ အချစ်ကို အပြည့်အဝရရှိပြီး ဘယ်လိုတွေ အလုပ်လုပ်ရင်း....",
"watch":"https://awscc3001.r18.com/litevideo/freepv/j/jul/jul00485/jul00485_dmb_w.mp4",
"download":"https://www.mediafire.com/file/xfd0oxjj13fv74a/JUL_485_-SD.mp4/file",
"photo1":"https://i.imgur.com/vTeGjcn_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/jul00485/jul00485pl.jpg",
"photo3":"https://pics.r18.com/digital/video/jul00485/jul00485jp-6.jpg",
"photo4":"https://pics.r18.com/digital/video/jul00485/jul00485jp-1.jpg",
"photo5":"https://pics.r18.com/digital/video/jul00485/jul00485jp-9.jpg",
"dapp":"https://www.mediafire.com/file/mvr4m1nbl2e14ia/JUL_485-HD.mp4/file",
"candownload":"",
"wcode":"တစ်"},
{"name":"RBD-804mmsub",
"info":"မြန်မာစာတန်းထိုး
လှပသော အိမ်ထောင်ရှင်မလေးအား 
ညှဉ်းပန်းနှိပ်စက်ပီး လိုးတဲ့ FA ကျော်ကြီး  
မင်းသမီး နာမည် Rina Ishihara",
"watch":"https://awscc3001.r18.com/litevideo/freepv/r/rbd/rbd00804/rbd00804_dmb_w.mp4",
"download":"https://www.mediafire.com/file/ateq3c5beaueuph/RBD-804.mp4/file",
"photo1":"https://i.imgur.com/P0CRQnw_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/rbd00804/rbd00804pl.jpg",
"photo3":"https://pics.dmm.co.jp/digital/video/rbd00804/rbd00804jp-2.jpg",
"photo4":"https://pics.dmm.co.jp/digital/video/rbd00804/rbd00804jp-10.jpg",
"photo5":"https://pics.dmm.co.jp/digital/video/rbd00804/rbd00804jp-6.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"URE-066mmdub",
"info":"မြန်မာစာတန်းထိုး
ကြောင်သူတော် ကြွက်သူခိုး MC လေးဟာဆိုရင် အပေါ်ယံကြည့်ရင် အင်မတန်မှ ရိုးသားပြီး ဘာမှအတွေ့အကြုံမရှိတဲ့ရုပ်ကလေးနဲ့ပါ ဒါကို အထင်သေးပြီး လူတတ်ကြီးလုပ်မိတဲ့ Asahi Mizuno တစ်ယောက် အိမ်ကွင်းကနေ အဝေးကွင်းသွားကန်ရတဲ့ခံစားချက်မျိုးအထိ ဖြစ်လာခဲ့ပါတယ်.....",
"watch":"https://awscc3001.r18.com/litevideo/freepv/u/ure/ure00066/ure00066_dmb_w.mp4",
"download":"https://www.mediafire.com/file/59jd6ekaz54pwv2/Ure_066-sd.mp4/file",
"photo1":"https://i.imgur.com/qcjLCMr_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/ure00066/ure00066pl.jpg",
"photo3":"https://pics.r18.com/digital/video/ure00066/ure00066jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/ure00066/ure00066jp-7.jpg",
"photo5":"https://pics.r18.com/digital/video/ure00066/ure00066jp-8.jpg",
"dapp":"https://www.mediafire.com/file/hxobg0ddf7h7tgd/URE_066-HD.mp4/file",
"candownload":"",
"wcode":"တစ်"},
{"name":"JUL-288mmsub",
"info":"မြန်မာစာတန်းထိုး
ယောကျာ်းရဲ့ ဝါသနာကို ဖြည့်ဆည်းပေးရင်းက
ခပ်အေးအေးနေတတ်တဲ့ Miho Tono တယောက် အထန်တလိုင်းဖြစ်သွားခဲ့ရတဲ့ ဇာတ်လမ်းလေးပါ သူ့ယောကျာ်းရဲ့ဝါသနာက ဘာဖြစ်မလဲဆိုတာကတော့...",
"watch":"https://awscc3001.r18.com/litevideo/freepv/j/jul/jul00288/jul00288_dmb_w.mp4",
"download":"https://www.mediafire.com/file/05srqaoysm1k5yu/Jul-288.mp4/file",
"photo1":"https://i.imgur.com/CFyLEQS_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/jul00288/jul00288pl.jpg",
"photo3":"https://pics.r18.com/digital/video/jul00288/jul00288jp-3.jpg",
"photo4":"https://pics.r18.com/digital/video/jul00288/jul00288jp-4.jpg",
"photo5":"https://pics.r18.com/digital/video/jul00288/jul00288jp-8.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"WAAA-022mmsub",
"info":"မြန်မာစာတန်းထိုး
ငါချစ်ရတဲ့သမီးလေးကို သနားညှာတာပြီး ချစ်ခြင်းမေတ္တာနဲ့ ကြီးပြင်းလာခဲ့သည်အထိ စောင့်ရှောက်ခဲ့ပါသည် 
 သူမဟာ ငါ့ရဲ့သမီးအရင်းမဟုတ်ဘဲ ဇနီးဖစ်သူက တခြားလူနဲ့ဖောက်ပြန်ပီး ရလာတဲ့ကလေးဖစ်တာကို DNA စစ်ပီး သိလိုက်ရတဲ့အခါ ကလဲ့စားချေခြင်း
ပြောင်ကြီးရဲ့ကလဲ့စားက ဘယ်လိုပုံစံဖစ်မလဲဆိုတာကိုတော့ ဇာတ်ကားတွင်ကြည့်ရှုလိုက်ပါ
မင်းသမီးနာမည်Akari Neo ",
"watch":"https://awscc3001.r18.com/litevideo/freepv/w/waa/waaa00022/waaa00022_dmb_w.mp4",
"download":"https://www.mediafire.com/file/fuovplrxuegoq02/WAAA+022-HD.mp4/file",
"photo1":"https://i.imgur.com/I9WM00T_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/waaa00022/waaa00022pl.jpg",
"photo3":"https://pics.r18.com/digital/video/waaa00022/waaa00022jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/waaa00022/waaa00022jp-2.jpg",
"photo5":"https://pics.r18.com/digital/video/waaa00022/waaa00022jp-3.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"JUL-296mmsub",
"info":"မြန်မာစာတန်းထိုး
နာမည်ကြီးမင်းသားဂျပန်ဂတုံး ပါဝင်သည်
မင်သမီးနာမည် Urara Kanon",
"watch":"https://awscc3001.r18.com/litevideo/freepv/j/jul/jul00296/jul00296_dmb_w.mp4",
"download":"https://www.mediafire.com/file/yr1kjbfidotaqmn/JUL-296.mp4/file",
"photo1":"https://i.imgur.com/t7J5Gou_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://pics.r18.com/digital/video/jul00296/jul00296pl.jpg",
"photo3":"https://pics.r18.com/digital/video/jul00296/jul00296jp-1.jpg",
"photo4":"https://pics.r18.com/digital/video/jul00296/jul00296jp-5.jpg",
"photo5":"https://pics.r18.com/digital/video/jul00296/jul00296jp-9.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"},
{"name":"ADN-100mmsub",
"info":"မြန်မာစာတန်းထိုး
JAV လောကထဲက အနားယူသွားပြီ ဖြစ်တဲ့ Saeko Matsushita ရဲ့ အ‌စောပိုင်းဇာတ်ကားလေးတစ်ကားကိုတင်ပေးလိုက်ပါတယ်။
ဒီကားမှာတော့ Saeko ဟာ ပန်းအလှဆင် သင်တန်းဆရာမဖြစ်ပြီး ယောက်ျားနဲ့အတူနေထိုင်နေရာက နေ ကြော်ငြာကုမ္ပဏီက Imai-san ဆိုတဲ့သူဟာ သင်တန်းကြော်ငြာထည့်ဖိုတောင်းဆိုတာကို ဆရာမလေး Saeko က ငြင်းလိုက်တဲ့အခါဘယတွေဆက်ဖြစ်မလဲကြည့်ရမှာဖြစ်ပါတယ်",
"watch":"https://cc3001.dmm.co.jp/litevideo/freepv/a/adn/adn00100/adn00100_dmb_w.mp4",
"download":"https://www.mediafire.com/file/mvg4lbg530j4y9r/ADN_100-HD.mp4/file",
"photo1":"https://i.imgur.com/I0QBuIw_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo2":"https://img2.javmost.com/file_image/ADN-100.jpg",
"photo3":"https://i.imgur.com/2GQLfyz_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo4":"https://i.imgur.com/uTAJQai_d.webp?maxwidth=640&shape=thumb&fidelity=medium",
"photo5":"https://nextjav.com/save/ADN-100/media/media-10-ADN-100.jpg",
"dapp":"t",
"candownload":"",
"wcode":"တစ်"}]
